./tester < ../../../data/1.in
./tester < ../../../data/2.in
./tester < ../../../data/3.in
./tester < ../../../data/4.in
./tester < ../../../data/5.in 
./tester < ../../../data/6.in
./tester < ../../../data/7.in
./tester < ../../../data/8.in
./tester < ../../../data/9.in
./tester < ../../../data/10.in
./tester < ../../../data/11.in
./tester < ../../../data/12.in
./tester < ../../../data/13.in
./tester < ../../../data/14.in
./tester < ../../../data/15.in 
./tester < ../../../data/16.in
./tester < ../../../data/17.in
./tester < ../../../data/18.in
./tester < ../../../data/19.in
./tester < ../../../data/20.in