java Main < ../../../data/1.in
java Main < ../../../data/2.in
java Main < ../../../data/3.in
java Main < ../../../data/4.in
java Main < ../../../data/5.in 
java Main < ../../../data/6.in
java Main < ../../../data/7.in
java Main < ../../../data/8.in
java Main < ../../../data/9.in
java Main < ../../../data/10.in
java Main < ../../../data/11.in
java Main < ../../../data/12.in
java Main < ../../../data/13.in
java Main < ../../../data/14.in
java Main < ../../../data/15.in 
java Main < ../../../data/16.in
java Main < ../../../data/17.in
java Main < ../../../data/18.in
java Main < ../../../data/19.in
java Main < ../../../data/20.in