[package]
name = "solutiont6"
version = "0.1.0"
edition = "2021"

[dependencies]
chinese-convert = { version = "0.1.0", path = "../../crates/chinese-convert" }

[[test]]
name = "tests"
path = "src/tests.rs"
