[package]
name = "solutiont2"
version = "0.1.0"
edition = "2021"

[dependencies]
dsu = { version = "0.1.0", path = "../../crates/dsu" }
serde = "1.0.215"
serde_json = "1.0.133"

[[test]]
name = "tests"
path = "src/tests.rs"
